# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Zil Patel
title: Computer Science Student
email: patelzp@myumanitoba.ca
website: https://github.com/patelzil

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  patelzil
instagram_username: zil.03
linkedin_username: zil-p-683657171
# dribbble_username:
# facebook_username:
# flickr_username:
# pinterest_username:
# youtube_username:

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/aboutimage.jpeg
about_content: | # this will include new lines to allow paragraphs
 Hi, my name is Zil and I am currently pursuing an undergraduate degree in Computer Science Honours at the University of Manitoba. 
 My fields of interest are Web Development, Artificial Intelligence, Machine learning and Databases.
 
 The languages and frameworks I have experience with are:
 <mark>Javascript</mark>,
 <mark>React</mark>,
 <mark>Node.js</mark>,
 <mark>Python</mark>
 <mark>Java</mark>,
 <mark>MongoDB</mark> and
 <mark>Git</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: E-book-hub
#         link: 
#         link_text: Link Text
        additional_links:
          - title:  patelzil/E-Book-Hub
            icon: fab fa-github
            url: https://github.com/patelzil/E-Book-Hub
        quote: >
          An application that interests its users towards reading e-books in an easily viewable layout.
        description: |
          - Languages/Frameworks/Tools: <mark>React</mark>, <mark>Node.js</mark>, <mark>Express.js</mark>, <mark>MongoDB</mark>, <mark>Docker</mark> and <mark>Git</mark>
          
          - Created UI using react.js and bootstrap allowing for integration with Google book API and MongoDB.  
          
          - Implemented chat feature using socket.io
          
          - Assisted in drawing the Architectural and Class diagrams for the application features.
          
      - layout: top-middle
        border: weak
        title: Skip the Service
        link: https://patelzil.github.io/skip-the-service/
        additional_links:
          - title:  patelzil/skip-the-service
            icon: fab fa-github
            url: https://github.com/patelzil/skip-the-service
        quote: >
          An application that allows homeowners to access services right from one convenient location.
        description: |
          - Languages/Frameworks/Tools: <mark>Java</mark>, <mark>Android Studio</mark>, <mark>SQLite</mark> and <mark>Gitlab</mark>
          
          - Made endpoints and queries for user and business accounts by linking the business and presentation layers using Java and SQLite.
          
          - Created UI for business and user locations using built-in Android libraries.
          
      - layout: top-middle
        border: weak
        title: Restaurant Search
        quote: >
          Search for restaurant in Winnipeg based on the food you want.
        description: |
          - Languages/Frameworks/Tools: <mark>Javascript</mark>, <mark>React Native</mark>, <mark>Visual Studio</mark> and <mark>Git</mark>
          
          - Made queries for user by linking the logic layer with Yelp API and connecting it to Presentation layer.
          
      - layout: top-middle
        title: Crave
        quote: >
          An online food ordering system integrated with online payment system.
        description: |
          - Languages/Frameworks/Tools: <mark>Javascript</mark>, <mark>HTML</mark>, <mark>CSS</mark> and <mark>Visual Studio</mark>
          
          - Made queries for user by linking the logic layer with Yelp API and connecting it to Presentation layer.
          
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Wawanesa Insurance
        sub_title: Administrative Assistant
        caption: June 2022 - Present
        link: https://www.wawanesa.com/canada/
#         quote: >
#           Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Perform data entry activities by assisting customers with changes and payment processes on policies.
          - Ensure all resource materials, including training materials, are kept up to date.
          
      - layout: left
        title: University of Manitoba
        sub_title: Teaching Assistant
        caption: January 2022 - April 2022
        description: |
          - Taught complex material to computer science students requiring additional help to improve understanding of the course material.
          - Graded lab quizzes of 75 undergraduate students, providing written feedback and ideas on a bi-weekly basis.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: University of Manitoba
        sub_title: Bachelor of Science in Computer Science, Honours.
        caption: Sept 2018 - May 2023

  - title: Extracurricular
    layout: list
    content:
      - layout: left
        title: BAPS
        sub_title: Volunteer and Peer Mentor
        caption: January 2014 - Present
        link: https://www.baps.org/
        description: |
          - Participated in locally organized walk green event to raise funds to support life-saving work of the William Osler Health System and Victoria General Foundation spearheaded by the BAPS.

#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in Web development and Machine Learning, some of my interests and hobbies are:
#       - Reading

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
